
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======

>>>>>>> bbf3a16dbdad2dd620584567f05cddd5f18f7e29
# Generated by Django 5.1.6 on 2025-03-15 05:32

# Generated by Django 5.1.6 on 2025-03-15 05:35

# Generated by Django 5.1.6 on 2025-03-15 05:31

>>>>>>> 1055ea29c50a71c058bcee443afaaf6e015a42bb

import django.db.models.deletion # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('taluka_id', models.AutoField(primary_key=True, serialize=False)),
                ('taluka_name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.district')),
            ],
            options={
                'db_table': 'tbl_taluka',
            },
        ),
    ]
