# Generated by Django 5.1.6 on 2025-03-15 12:15

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('taluka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taluka',
            name='taluka_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='temp-slug', editable=False, populate_from='taluka_name', unique=True),
        ),
        migrations.AlterField(
            model_name='taluka',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district'),
        ),
    ]
