# Generated by Django 5.1.6 on 2025-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taluka', '0002_taluka_taluka_slug_alter_taluka_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taluka',
            name='taluka_slug',
        ),
        migrations.AlterField(
            model_name='taluka',
            name='taluka_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
