# Generated by Django 5.1.6 on 2025-03-15 16:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taluka', '0003_remove_taluka_taluka_slug_alter_taluka_taluka_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taluka',
            name='taluka_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='taluka_name', unique=True),
        ),
    ]
