# Generated by Django 5.1.6 on 2025-03-15 16:59

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taluka', '0004_taluka_taluka_slug'),
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='village_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='village_name', unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taluka.taluka'),
        ),
    ]
