# Generated by Django 5.1.6 on 2025-03-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_fullNameEng', models.CharField(max_length=255)),
                ('c_fullNameMarathi', models.CharField(max_length=255)),
                ('c_mobile', models.CharField(max_length=255)),
                ('c_birthDate', models.CharField(max_length=255)),
                ('c_pinCode', models.CharField(max_length=255)),
                ('c_email', models.CharField(max_length=255)),
                ('c_password', models.CharField(max_length=255)),
            ],
        ),
    ]
