# Generated by Django 5.1.6 on 2025-03-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('district', '0001_initial'),
        ('franchise', '0001_initial'),
        ('state', '0001_initial'),
        ('taluka', '0001_initial'),
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district'),
        ),
        migrations.AddField(
            model_name='customer',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.state'),
        ),
        migrations.AddField(
            model_name='customer',
            name='taluka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taluka.taluka'),
        ),
        migrations.AddField(
            model_name='customer',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='village.village'),
        ),
    ]
