<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-17 05:29

from django.db import migrations
# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore
=======
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-16 04:42

from django.db import migrations
=======
<<<<<<< HEAD
=======

>>>>>>> 6917f9d8003454914e142858669faf01439252c9
# Generated by Django 5.1.6 on 2025-03-17 05:29

from django.db import migrations
<<<<<<< HEAD

# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore

=======
# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore
<<<<<<< HEAD
>>>>>>> 1d49f8902c95651f49d6abae033697f4725484d1
>>>>>>> 2f2f0b70e295b8e1f1085407c35492ce0ecbf8b9
=======
>>>>>>> 3a5d205939989e96a82c8d642034e2c794a24292
>>>>>>> 6917f9d8003454914e142858669faf01439252c9
>>>>>>> 0bc1a29285792c0513335d30e90703a7e53f9dac


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_district_customer_franchise_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customer',
        ),
    ]
