<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-17 05:29

from django.db import migrations
=======
# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore
>>>>>>> 1d49f8902c95651f49d6abae033697f4725484d1


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_district_customer_franchise_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customer',
        ),
    ]
