
<<<<<<< HEAD
=======
<<<<<<< HEAD
from django.db import migrations
# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore
# Generated by Django 5.1.6 on 2025-03-16 04:42

from django.db import migrations
# Generated by Django 5.1.6 on 2025-03-17 05:29

from django.db import migrations
=======
<<<<<<< HEAD
=======

# Generated by Django 5.1.6 on 2025-03-16 04:42

from django.db import migrations



# Generated by Django 5.1.6 on 2025-03-17 05:29

from django.db import migrations
>>>>>>> c3ff6351cba315efba4ac0c4534c45963d600287
>>>>>>> 6f1cf956187c29018c3db3d80ddcd44812aeafe7

# Generated by Django 5.1.6 on 2025-03-17 05:29

from django.db import migrations # type: ignore
# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore

# Generated by Django 5.1.6 on 2025-03-16 04:42

from django.db import migrations # type: ignore


# Generated by Django 5.1.6 on 2025-03-17 05:29



>>>>>>> 418d82337c0c3efc68bc38801b9d6e9805136440

# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore

<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore
=======


<<<<<<< HEAD
=======
from django.db import migrations # type: ignore


# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations # type: ignore

>>>>>>> c3ff6351cba315efba4ac0c4534c45963d600287
>>>>>>> 418d82337c0c3efc68bc38801b9d6e9805136440
>>>>>>> 6f1cf956187c29018c3db3d80ddcd44812aeafe7


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_district_customer_franchise_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customer',
        ),
    ]
