# Generated by Django 5.1.6 on 2025-03-18 07:22

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('product_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='product_name', unique=True)),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.tax')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
