# Generated by Django 5.1.6 on 2025-03-22 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternateunit', '0001_initial'),
        ('product', '0003_product_primaryunit_product_product_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternateunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alternateunit.alternateunit'),
        ),
    ]
