# Generated by Django 5.1.6 on 2025-03-15 04:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.AutoField(primary_key=True, serialize=False)),
                ('franchise_name', models.CharField(max_length=255, null=True)),
                ('franchise_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='franchise_name', unique=True)),
            ],
            options={
                'db_table': 'tbl_franchise',
            },
        ),
    ]
