# Generated by Django 5.1.6 on 2025-03-26 04:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchise_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='franchise_name', unique=True),
        ),
    ]
