# Generated by Django 5.1.6 on 2025-03-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Online Transfer')], max_length=10, null=True),
        ),
    ]
