# Generated by Django 5.1.6 on 2025-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('taxtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('taxtype_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tbl_taxtype',
            },
        ),
    ]
