# Generated by Django 5.1.6 on 2025-03-21 05:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='taxtype_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='taxtype_name', unique=True),
        ),
    ]
