# Generated by Django 5.1.6 on 2025-03-21 05:01

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='taxtype_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='taxtype_name', unique=True),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='taxtype_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
