# Generated by Django 5.1.6 on 2025-03-21 04:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('contact_email', models.CharField(max_length=255, null=True)),
                ('contact_enquiry', models.CharField(max_length=255, null=True)),
                ('contact_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='contact_name', unique=True)),
            ],
            options={
                'db_table': 'tbl_contact',
            },
        ),
    ]
