# Generated by Django 5.1.6 on 2025-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_slider',
            },
        ),
    ]
