# Generated by Django 5.1.6 on 2025-03-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_alter_customer_table'),
        ('product', '0005_product_barcode_product_exp_date_product_mfg_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_quantity', models.CharField(max_length=255)),
                ('cart_img', models.ImageField(null=True, upload_to='')),
                ('cart_price', models.CharField(max_length=255)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
