
<<<<<<< HEAD
=======
# Generated by Django 5.1.6 on 2025-03-25 05:38


# Generated by Django 5.1.6 on 2025-03-25 05:39



# Generated by Django 5.1.6 on 2025-03-26 04:06

>>>>>>> ef22782e8531a57de9b5a79d6fccaa9f13fc5bcd
# Generated by Django 5.1.6 on 2025-03-25 06:44

# Generated by Django 5.1.6 on 2025-03-25 05:37

<<<<<<< HEAD
=======

# Generated by Django 5.1.6 on 2025-03-26 04:0
# Generated by Django 5.1.6 on 2025-03-25 06:
# Generated by Django 5.1.6 on 2025-03-25 05:37



>>>>>>> ef22782e8531a57de9b5a79d6fccaa9f13fc5bcd

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_img',
        ),
    ]
