<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-26 04:06
=======
<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-25 06:44
=======
# Generated by Django 5.1.6 on 2025-03-25 05:37
>>>>>>> 65c6ce3bf6d88db4bd9322dbdf5b2f22534cfb4b
>>>>>>> 23654bcd59c452d4a4b309c53ec8c34ece2e2340

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_img',
        ),
    ]
