# Generated by Django 5.1.6 on 2025-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_cart_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
