# Generated by Django 5.1.6 on 2025-03-15 04:59

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255)),
                ('district_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='district_name', unique=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
            options={
                'db_table': 'tbl_district',
            },
        ),
    ]
