# Generated by Django 5.1.6 on 2025-03-15 04:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('state_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='state_name', unique=True)),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
    ]
