
# Generated by Django 5.1.6 on 2025-03-21 04:33

# Generated by Django 5.1.6 on 2025-03-18 07:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
